//----------------------
// <auto-generated>
//     Generated using the NJsonSchema v10.8.0.0 (Newtonsoft.Json v13.0.3.0) (http://NJsonSchema.org)
// </auto-generated>
//----------------------

namespace InvoizR.SharedKernel.Mh.Anulacion;

#pragma warning disable // Disable all warnings

[System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "10.8.0.0 (Newtonsoft.Json v13.0.3.0)")]
public partial class Anulacionv2 : Dte
{
    /// <summary>
    /// Informacion de identificacion de Invalidacion
    /// </summary>

    [System.Text.Json.Serialization.JsonPropertyName("identificacion")]

    [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
    [System.ComponentModel.DataAnnotations.Required]
    public Identificacion Identificacion { get; set; } = new Identificacion();

    /// <summary>
    /// Datos del emisor
    /// </summary>

    [System.Text.Json.Serialization.JsonPropertyName("emisor")]

    [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
    [System.ComponentModel.DataAnnotations.Required]
    public Emisor Emisor { get; set; } = new Emisor();

    /// <summary>
    /// Datos del documento a Invalidar
    /// </summary>

    [System.Text.Json.Serialization.JsonPropertyName("documento")]

    [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
    [System.ComponentModel.DataAnnotations.Required]
    public Documento Documento { get; set; } = new Documento();

    /// <summary>
    /// Datos del motivo de Invalidacion
    /// </summary>

    [System.Text.Json.Serialization.JsonPropertyName("motivo")]

    [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
    [System.ComponentModel.DataAnnotations.Required]
    public Motivo Motivo { get; set; } = new Motivo();


}

[System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "10.8.0.0 (Newtonsoft.Json v13.0.3.0)")]
public partial class Identificacion
{
    /// <summary>
    /// Version del esquema
    /// </summary>

    [System.Text.Json.Serialization.JsonPropertyName("version")]

    [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
    public int Version { get; set; }

    /// <summary>
    /// Ambiente de destino: 00 - Pruebas, 01 - Produccion
    /// </summary>

    [System.Text.Json.Serialization.JsonPropertyName("ambiente")]

    [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]
    [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
    //[System.Text.Json.Serialization.JsonConverter(typeof(System.Text.Json.Serialization.JsonStringEnumConverter))]
    //public IdentificacionAmbiente Ambiente { get; set; }
    public string Ambiente { get; set; }

    /// <summary>
    /// Codigo Generacion
    /// </summary>

    [System.Text.Json.Serialization.JsonPropertyName("codigoGeneracion")]

    [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
    [System.ComponentModel.DataAnnotations.Required]
    [System.ComponentModel.DataAnnotations.StringLength(36, MinimumLength = 36)]
    [System.ComponentModel.DataAnnotations.RegularExpression(@"^[A-F0-9]{8}-[A-F0-9]{4}-[A-F0-9]{4}-[A-F0-9]{4}-[A-F0-9]{12}$")]
    public string CodigoGeneracion { get; set; }

    /// <summary>
    /// Fecha de invalidacion (formato yyyy-mm-dd)
    /// </summary>

    [System.Text.Json.Serialization.JsonPropertyName("fecAnula")]

    [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
    [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
    [System.Text.Json.Serialization.JsonConverter(typeof(DateFormatConverter))]
    public System.DateTimeOffset FecAnula { get; set; }

    /// <summary>
    /// Hora de invalidacion
    /// </summary>

    [System.Text.Json.Serialization.JsonPropertyName("horAnula")]

    [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
    [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
    [System.ComponentModel.DataAnnotations.RegularExpression(@"^(0[0-9]|1[0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9]?$")]
    public string HorAnula { get; set; }


}

[System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "10.8.0.0 (Newtonsoft.Json v13.0.3.0)")]
public partial class Emisor
{
    /// <summary>
    /// NIT, sin guiones
    /// </summary>

    [System.Text.Json.Serialization.JsonPropertyName("nit")]

    [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
    [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
    [System.ComponentModel.DataAnnotations.RegularExpression(@"^([0-9]{14}|[0-9]{9})$")]
    public string Nit { get; set; }

    /// <summary>
    /// Nombre/Denominacion/Razon social
    /// </summary>

    [System.Text.Json.Serialization.JsonPropertyName("nombre")]

    [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
    [System.ComponentModel.DataAnnotations.Required]
    [System.ComponentModel.DataAnnotations.StringLength(250, MinimumLength = 3)]
    public string Nombre { get; set; }

    /// <summary>
    /// Tipo establecimiento donde se emite documento
    /// </summary>

    [System.Text.Json.Serialization.JsonPropertyName("tipoEstablecimiento")]

    [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
    [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
    [System.Text.Json.Serialization.JsonConverter(typeof(System.Text.Json.Serialization.JsonStringEnumConverter))]
    public EmisorTipoEstablecimiento TipoEstablecimiento { get; set; }

    /// <summary>
    /// Nombre de establecimiento
    /// </summary>

    [System.Text.Json.Serialization.JsonPropertyName("nomEstablecimiento")]

    [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
    [System.ComponentModel.DataAnnotations.StringLength(150, MinimumLength = 3)]
    public string NomEstablecimiento { get; set; }

    /// <summary>
    /// Codigo, Numero o Identificador de establecimiento por MH
    /// </summary>

    [System.Text.Json.Serialization.JsonPropertyName("codEstableMH")]

    [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]   
    [System.ComponentModel.DataAnnotations.StringLength(4, MinimumLength = 4)]
    public string CodEstableMH { get; set; }

    /// <summary>
    /// Codigo, Numero o Identificador de establecimiento por Contribuyente
    /// </summary>

    [System.Text.Json.Serialization.JsonPropertyName("codEstable")]

    [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
    [System.ComponentModel.DataAnnotations.StringLength(10, MinimumLength = 1)]
    public string CodEstable { get; set; }

    /// <summary>
    /// Codigo, Numero o Identificador de punto de venta por MH
    /// </summary>

    [System.Text.Json.Serialization.JsonPropertyName("codPuntoVentaMH")]

    [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]   
    [System.ComponentModel.DataAnnotations.StringLength(4, MinimumLength = 4)]
    public string CodPuntoVentaMH { get; set; }

    /// <summary>
    /// Codigo, Numero o Identificador de punto de venta por Contribuyente
    /// </summary>

    [System.Text.Json.Serialization.JsonPropertyName("codPuntoVenta")]

    [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
    [System.ComponentModel.DataAnnotations.StringLength(15, MinimumLength = 1)]
    public string CodPuntoVenta { get; set; }

    /// <summary>
    /// Numero de telefono del emisor
    /// </summary>

    [System.Text.Json.Serialization.JsonPropertyName("telefono")]

    [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
    [System.ComponentModel.DataAnnotations.StringLength(26, MinimumLength = 8)]
    [System.ComponentModel.DataAnnotations.RegularExpression(@"^[0-9+;]{8,26}$")]
    public string Telefono { get; set; }

    /// <summary>
    /// Correo electronico del emisor
    /// </summary>

    [System.Text.Json.Serialization.JsonPropertyName("correo")]

    [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
    [System.ComponentModel.DataAnnotations.Required]
    [System.ComponentModel.DataAnnotations.StringLength(100, MinimumLength = 3)]
    public string Correo { get; set; }


}

[System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "10.8.0.0 (Newtonsoft.Json v13.0.3.0)")]
public partial class Documento
{
    /// <summary>
    /// Tipo de documento
    /// </summary>

    [System.Text.Json.Serialization.JsonPropertyName("tipoDte")]

    [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
    [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
    [System.ComponentModel.DataAnnotations.RegularExpression(@"^0[0-9]|1[0-5]$")]
    [System.Text.Json.Serialization.JsonConverter(typeof(System.Text.Json.Serialization.JsonStringEnumConverter))]
    public DocumentoTipoDte TipoDte { get; set; }

    /// <summary>
    /// Codigo Generacion
    /// </summary>

    [System.Text.Json.Serialization.JsonPropertyName("codigoGeneracion")]

    [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
    [System.ComponentModel.DataAnnotations.Required]
    [System.ComponentModel.DataAnnotations.StringLength(36, MinimumLength = 36)]
    [System.ComponentModel.DataAnnotations.RegularExpression(@"^[A-F0-9]{8}-[A-F0-9]{4}-[A-F0-9]{4}-[A-F0-9]{4}-[A-F0-9]{12}$")]
    public string CodigoGeneracion { get; set; }

    /// <summary>
    /// Sello de recepcion
    /// </summary>

    [System.Text.Json.Serialization.JsonPropertyName("selloRecibido")]

    [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
    [System.ComponentModel.DataAnnotations.Required]
    [System.ComponentModel.DataAnnotations.StringLength(40, MinimumLength = 40)]
    [System.ComponentModel.DataAnnotations.RegularExpression(@"^[A-Z0-9]{40}$")]
    public string SelloRecibido { get; set; }

    /// <summary>
    /// Numero control
    /// </summary>

    [System.Text.Json.Serialization.JsonPropertyName("numeroControl")]

    [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
    [System.ComponentModel.DataAnnotations.Required]
    [System.ComponentModel.DataAnnotations.StringLength(31, MinimumLength = 31)]
    [System.ComponentModel.DataAnnotations.RegularExpression(@"^DTE-0[0-9]|1[0-2]-[A-Z0-9]{8}-[0-9]{15}$")]
    public string NumeroControl { get; set; }

    /// <summary>
    /// Fecha de emision (formato yyyy-mm-dd)
    /// </summary>

    [System.Text.Json.Serialization.JsonPropertyName("fecEmi")]

    [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
    [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
    [System.Text.Json.Serialization.JsonConverter(typeof(DateFormatConverter))]
    public System.DateTimeOffset FecEmi { get; set; }

    /// <summary>
    /// Monto IVA
    /// </summary>

    [System.Text.Json.Serialization.JsonPropertyName("montoIva")]

    [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
    [System.ComponentModel.DataAnnotations.Range(0D, double.MaxValue)]
    public double? MontoIva { get; set; }

    /// <summary>
    /// Codigo Generacion que reemplaza
    /// </summary>

    [System.Text.Json.Serialization.JsonPropertyName("codigoGeneracionR")]

    [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
    [System.ComponentModel.DataAnnotations.StringLength(36, MinimumLength = 36)]
    [System.ComponentModel.DataAnnotations.RegularExpression(@"^[A-F0-9]{8}-[A-F0-9]{4}-[A-F0-9]{4}-[A-F0-9]{4}-[A-F0-9]{12}$")]
    public string CodigoGeneracionR { get; set; }

    /// <summary>
    /// Tipo documento de identificación CAT-22: 36 - NIT, 13 - DUI, 02 - Carnet de residente, 03 - PASAPORTE, 37 - OTRO
    /// </summary>

    [System.Text.Json.Serialization.JsonPropertyName("tipoDocumento")]

    [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
    [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
    [System.Text.Json.Serialization.JsonConverter(typeof(System.Text.Json.Serialization.JsonStringEnumConverter))]
    public DocumentoTipoDocumento TipoDocumento { get; set; }

    /// <summary>
    /// Número de documento de Identificación 
    /// </summary>

    [System.Text.Json.Serialization.JsonPropertyName("numDocumento")]

    [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
    [System.ComponentModel.DataAnnotations.Required]
    [System.ComponentModel.DataAnnotations.StringLength(20, MinimumLength = 3)]
    public string NumDocumento { get; set; }

    /// <summary>
    /// Nombre/Denominacion/Razon social
    /// </summary>

    [System.Text.Json.Serialization.JsonPropertyName("nombre")]

    [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
    [System.ComponentModel.DataAnnotations.Required]
    [System.ComponentModel.DataAnnotations.StringLength(200, MinimumLength = 5)]
    public string Nombre { get; set; }

    /// <summary>
    /// Numero de telefono del receptor
    /// </summary>

    [System.Text.Json.Serialization.JsonPropertyName("telefono")]

    [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]   
    [System.ComponentModel.DataAnnotations.StringLength(50, MinimumLength = 8)]
    [System.ComponentModel.DataAnnotations.RegularExpression(@"^[0-9+;]{8,50}$")]
    public string Telefono { get; set; }

    /// <summary>
    /// Correo electronico del receptor
    /// </summary>

    [System.Text.Json.Serialization.JsonPropertyName("correo")]

    [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]   
    [System.ComponentModel.DataAnnotations.StringLength(100)]
    public string Correo { get; set; }


}

[System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "10.8.0.0 (Newtonsoft.Json v13.0.3.0)")]
public partial class Motivo : object
{
    /// <summary>
    /// Tipo de invalidacion
    /// </summary>

    [System.Text.Json.Serialization.JsonPropertyName("tipoAnulacion")]

    [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
    public MotivoTipoAnulacion TipoAnulacion { get; set; }

    /// <summary>
    /// Motivo de invalidacion
    /// </summary>

    [System.Text.Json.Serialization.JsonPropertyName("motivoAnulacion")]

    [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
    [System.ComponentModel.DataAnnotations.StringLength(250, MinimumLength = 5)]
    public string MotivoAnulacion { get; set; }

    /// <summary>
    /// Nombre de la persona responsable de invalidar el DTE
    /// </summary>

    [System.Text.Json.Serialization.JsonPropertyName("nombreResponsable")]

    [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
    [System.ComponentModel.DataAnnotations.Required]
    [System.ComponentModel.DataAnnotations.StringLength(100, MinimumLength = 5)]
    public string NombreResponsable { get; set; }

    /// <summary>
    /// Tipo documento de identificación CAT-22: 36 - NIT, 13 - DUI, 02 - Carnet de residente, 03 - PASAPORTE, 37 - OTRO
    /// </summary>

    [System.Text.Json.Serialization.JsonPropertyName("tipDocResponsable")]

    [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]
    [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
    //[System.Text.Json.Serialization.JsonConverter(typeof(System.Text.Json.Serialization.JsonStringEnumConverter))]
    //public MotivoTipDocResponsable TipDocResponsable { get; set; }
    public string TipDocResponsable { get; set; }

    /// <summary>
    /// Número de documento de identificación 
    /// </summary>

    [System.Text.Json.Serialization.JsonPropertyName("numDocResponsable")]

    [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
    [System.ComponentModel.DataAnnotations.Required]
    [System.ComponentModel.DataAnnotations.StringLength(20, MinimumLength = 3)]
    public string NumDocResponsable { get; set; }

    /// <summary>
    /// Nombre de la persona que solicita invalidar el DTE
    /// </summary>

    [System.Text.Json.Serialization.JsonPropertyName("nombreSolicita")]

    [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
    [System.ComponentModel.DataAnnotations.Required]
    [System.ComponentModel.DataAnnotations.StringLength(100, MinimumLength = 5)]
    public string NombreSolicita { get; set; }

    /// <summary>
    /// Tipo documento de identificación solicitante CAT-22: 36 - NIT, 13 - DUI, 02 - Carnet de residente, 03 - PASAPORTE, 37 - OTRO
    /// </summary>

    [System.Text.Json.Serialization.JsonPropertyName("tipDocSolicita")]

    [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
    [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
    [System.Text.Json.Serialization.JsonConverter(typeof(System.Text.Json.Serialization.JsonStringEnumConverter))]
    public MotivoTipDocSolicita TipDocSolicita { get; set; }

    /// <summary>
    /// Número de documento de identificación solicitante.
    /// </summary>

    [System.Text.Json.Serialization.JsonPropertyName("numDocSolicita")]

    [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
    [System.ComponentModel.DataAnnotations.Required]
    [System.ComponentModel.DataAnnotations.StringLength(20, MinimumLength = 3)]
    public string NumDocSolicita { get; set; }


}

[System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "10.8.0.0 (Newtonsoft.Json v13.0.3.0)")]
public enum IdentificacionAmbiente
{

    [System.Runtime.Serialization.EnumMember(Value = @"00")]
    _00 = 0,


    [System.Runtime.Serialization.EnumMember(Value = @"01")]
    _01 = 1,


}

[System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "10.8.0.0 (Newtonsoft.Json v13.0.3.0)")]
public enum EmisorTipoEstablecimiento
{

    [System.Runtime.Serialization.EnumMember(Value = @"01")]
    _01 = 0,


    [System.Runtime.Serialization.EnumMember(Value = @"02")]
    _02 = 1,


    [System.Runtime.Serialization.EnumMember(Value = @"04")]
    _04 = 2,


    [System.Runtime.Serialization.EnumMember(Value = @"07")]
    _07 = 3,


    [System.Runtime.Serialization.EnumMember(Value = @"20")]
    _20 = 4,


}

[System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "10.8.0.0 (Newtonsoft.Json v13.0.3.0)")]
public enum DocumentoTipoDte
{

    [System.Runtime.Serialization.EnumMember(Value = @"01")]
    _01 = 0,


    [System.Runtime.Serialization.EnumMember(Value = @"03")]
    _03 = 1,


    [System.Runtime.Serialization.EnumMember(Value = @"04")]
    _04 = 2,


    [System.Runtime.Serialization.EnumMember(Value = @"05")]
    _05 = 3,


    [System.Runtime.Serialization.EnumMember(Value = @"06")]
    _06 = 4,


    [System.Runtime.Serialization.EnumMember(Value = @"07")]
    _07 = 5,


    [System.Runtime.Serialization.EnumMember(Value = @"08")]
    _08 = 6,


    [System.Runtime.Serialization.EnumMember(Value = @"09")]
    _09 = 7,


    [System.Runtime.Serialization.EnumMember(Value = @"10")]
    _10 = 8,


    [System.Runtime.Serialization.EnumMember(Value = @"11")]
    _11 = 9,


    [System.Runtime.Serialization.EnumMember(Value = @"14")]
    _14 = 10,


    [System.Runtime.Serialization.EnumMember(Value = @"15")]
    _15 = 11,


}

[System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "10.8.0.0 (Newtonsoft.Json v13.0.3.0)")]
public enum DocumentoTipoDocumento
{

    [System.Runtime.Serialization.EnumMember(Value = @"36")]
    _36 = 0,


    [System.Runtime.Serialization.EnumMember(Value = @"13")]
    _13 = 1,


    [System.Runtime.Serialization.EnumMember(Value = @"02")]
    _02 = 2,


    [System.Runtime.Serialization.EnumMember(Value = @"03")]
    _03 = 3,


    [System.Runtime.Serialization.EnumMember(Value = @"37")]
    _37 = 4,


}

[System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "10.8.0.0 (Newtonsoft.Json v13.0.3.0)")]
public enum MotivoTipoAnulacion
{

    _1 = 1,


    _2 = 2,


    _3 = 3,


}

[System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "10.8.0.0 (Newtonsoft.Json v13.0.3.0)")]
public enum MotivoTipDocResponsable
{

    [System.Runtime.Serialization.EnumMember(Value = @"36")]
    _36 = 0,


    [System.Runtime.Serialization.EnumMember(Value = @"13")]
    _13 = 1,


    [System.Runtime.Serialization.EnumMember(Value = @"02")]
    _02 = 2,


    [System.Runtime.Serialization.EnumMember(Value = @"03")]
    _03 = 3,


    [System.Runtime.Serialization.EnumMember(Value = @"37")]
    _37 = 4,


}

[System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "10.8.0.0 (Newtonsoft.Json v13.0.3.0)")]
public enum MotivoTipDocSolicita
{

    [System.Runtime.Serialization.EnumMember(Value = @"36")]
    _36 = 0,


    [System.Runtime.Serialization.EnumMember(Value = @"13")]
    _13 = 1,


    [System.Runtime.Serialization.EnumMember(Value = @"02")]
    _02 = 2,


    [System.Runtime.Serialization.EnumMember(Value = @"03")]
    _03 = 3,


    [System.Runtime.Serialization.EnumMember(Value = @"37")]
    _37 = 4,


}

[System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "10.8.0.0 (Newtonsoft.Json v13.0.3.0)")]
internal class DateFormatConverter : System.Text.Json.Serialization.JsonConverter<System.DateTimeOffset>
{
    public override System.DateTimeOffset Read(ref System.Text.Json.Utf8JsonReader reader, System.Type typeToConvert, System.Text.Json.JsonSerializerOptions options)
    {
        var dateTime = reader.GetString();
        if (dateTime == null)
        {
            throw new System.Text.Json.JsonException("Unexpected JsonTokenType.Null");
        }

        return System.DateTimeOffset.Parse(dateTime);
    }

    public override void Write(System.Text.Json.Utf8JsonWriter writer, System.DateTimeOffset value, System.Text.Json.JsonSerializerOptions options)
    {
        writer.WriteStringValue(value.ToString("yyyy-MM-dd"));
    }
}