//----------------------
// <auto-generated>
//     Generated using the NJsonSchema v10.8.0.0 (Newtonsoft.Json v13.0.3.0) (http://NJsonSchema.org)
// </auto-generated>
//----------------------

namespace InvoizR.SharedKernel.Mh.Contingencia;

#pragma warning disable // Disable all warnings

/// <summary>
/// The root schema comprises the entire JSON document.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "10.8.0.0 (Newtonsoft.Json v13.0.3.0)")]
public partial class Contingenciav3 : Dte
{
    /// <summary>
    /// An explanation about the purpose of this instance.
    /// </summary>

    [System.Text.Json.Serialization.JsonPropertyName("identificacion")]

    [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]
    [System.ComponentModel.DataAnnotations.Required]
    public Identificacion Identificacion { get; set; } = new Identificacion();

    /// <summary>
    /// Informacion del emisor.
    /// </summary>

    [System.Text.Json.Serialization.JsonPropertyName("emisor")]

    [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]
    [System.ComponentModel.DataAnnotations.Required]
    public Emisor Emisor { get; set; } = new Emisor();

    /// <summary>
    /// Detalle de los documentos que se enviaran en contingencia.
    /// </summary>

    [System.Text.Json.Serialization.JsonPropertyName("detalleDTE")]

    [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]
    [System.ComponentModel.DataAnnotations.Required]
    [System.ComponentModel.DataAnnotations.MinLength(1)]
    [System.ComponentModel.DataAnnotations.MaxLength(1000)]
    public System.Collections.Generic.ICollection<DetalleDTE> DetalleDTE { get; set; } = new System.Collections.ObjectModel.Collection<DetalleDTE>();

    /// <summary>
    /// Motivo de la contingenia.
    /// </summary>

    [System.Text.Json.Serialization.JsonPropertyName("motivo")]

    [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]
    [System.ComponentModel.DataAnnotations.Required]
    public Motivo Motivo { get; set; } = new Motivo();


}

[System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "10.8.0.0 (Newtonsoft.Json v13.0.3.0)")]
public partial class Identificacion
{
    /// <summary>
    /// Version del esquema del DTE
    /// </summary>

    [System.Text.Json.Serialization.JsonPropertyName("version")]

    [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]
    public int Version { get; set; }

    /// <summary>
    /// Ambiente de destino: 00 - Pruebas, 01 - Produccion
    /// </summary>

    [System.Text.Json.Serialization.JsonPropertyName("ambiente")]

    [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]
    [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
    //[System.Text.Json.Serialization.JsonConverter(typeof(System.Text.Json.Serialization.JsonStringEnumConverter))]
    //public IdentificacionAmbiente Ambiente { get; set; }
    public string Ambiente { get; set; }

    /// <summary>
    /// Debe cumplir con el estandar del UUID v4, el cual Debe ser unico por evento de contingencia (el cual no debe repetirse) longitud de 36 digitos sin guiones codigo de generacion consiste en un numero identificador inico, aleatorio y universal.
    /// </summary>

    [System.Text.Json.Serialization.JsonPropertyName("codigoGeneracion")]

    [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]
    [System.ComponentModel.DataAnnotations.Required]
    [System.ComponentModel.DataAnnotations.StringLength(36, MinimumLength = 36)]
    [System.ComponentModel.DataAnnotations.RegularExpression(@"^[A-F0-9]{8}-[A-F0-9]{4}-[A-F0-9]{4}-[A-F0-9]{4}-[A-F0-9]{12}$")]
    public string CodigoGeneracion { get; set; }

    /// <summary>
    /// Fecha de emision (formato yyyy-mm-dd)
    /// </summary>

    [System.Text.Json.Serialization.JsonPropertyName("fTransmision")]

    [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]
    [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
    [System.Text.Json.Serialization.JsonConverter(typeof(DateFormatConverter))]
    public System.DateTimeOffset FTransmision { get; set; }

    /// <summary>
    /// Hora de emision
    /// </summary>

    [System.Text.Json.Serialization.JsonPropertyName("hTransmision")]

    [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]
    [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
    [System.ComponentModel.DataAnnotations.RegularExpression(@"^(0[0-9]|1[0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9]?$")]
    public string HTransmision { get; set; }


}

[System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "10.8.0.0 (Newtonsoft.Json v13.0.3.0)")]
public partial class Emisor
{
    /// <summary>
    /// NIT, sin guiones
    /// </summary>

    [System.Text.Json.Serialization.JsonPropertyName("nit")]

    [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]
    [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
    [System.ComponentModel.DataAnnotations.RegularExpression(@"^([0-9]{14}|[0-9]{9})$")]
    public string Nit { get; set; }

    /// <summary>
    /// Nombre, denominación o  razón social del contribuyente (EMISOR)
    /// </summary>

    [System.Text.Json.Serialization.JsonPropertyName("nombre")]

    [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]
    [System.ComponentModel.DataAnnotations.Required]
    [System.ComponentModel.DataAnnotations.StringLength(250, MinimumLength = 5)]
    public string Nombre { get; set; }

    /// <summary>
    /// NOMBRE DEL RESPONSABLE DEL ESTABLECIMIENTO.
    /// </summary>

    [System.Text.Json.Serialization.JsonPropertyName("nombreResponsable")]

    [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]
    [System.ComponentModel.DataAnnotations.Required]
    [System.ComponentModel.DataAnnotations.StringLength(100, MinimumLength = 5)]
    public string NombreResponsable { get; set; }

    /// <summary>
    /// Tipo documento de identificación del responsable CAT-22: 36 - NIT, 13 - DUI, 02 - Carnet de residente, 03 - PASAPORTE, 37 - OTRO
    /// </summary>

    [System.Text.Json.Serialization.JsonPropertyName("tipoDocResponsable")]

    [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]
    [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
    [System.Text.Json.Serialization.JsonConverter(typeof(System.Text.Json.Serialization.JsonStringEnumConverter))]
    public EmisorTipoDocResponsable TipoDocResponsable { get; set; }

    /// <summary>
    /// NUMERO DE DOCUMENTO DE IDENTIFICACION DEL RESPONSABLE.
    /// </summary>

    [System.Text.Json.Serialization.JsonPropertyName("numeroDocResponsable")]

    [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]
    [System.ComponentModel.DataAnnotations.Required]
    [System.ComponentModel.DataAnnotations.StringLength(25, MinimumLength = 5)]
    public string NumeroDocResponsable { get; set; }

    /// <summary>
    /// TIPO DE ESTABLECIMIENTO (EMISOR) (QUE HA ENTRADO EN CONTINGENCIA)
    /// </summary>

    [System.Text.Json.Serialization.JsonPropertyName("tipoEstablecimiento")]

    [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]
    [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
    [System.Text.Json.Serialization.JsonConverter(typeof(System.Text.Json.Serialization.JsonStringEnumConverter))]
    public EmisorTipoEstablecimiento TipoEstablecimiento { get; set; }

    /// <summary>
    /// Codigo, Numero o Identificador de establecimiento por MH
    /// </summary>

    [System.Text.Json.Serialization.JsonPropertyName("codEstableMH")]

    [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]
    [System.ComponentModel.DataAnnotations.StringLength(4, MinimumLength = 4)]
    public string CodEstableMH { get; set; }

    /// <summary>
    /// Codigo, Numero o Identificador de punto de venta por Contribuyente
    /// </summary>

    [System.Text.Json.Serialization.JsonPropertyName("codPuntoVenta")]

    [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]
    [System.ComponentModel.DataAnnotations.StringLength(15, MinimumLength = 1)]
    public string CodPuntoVenta { get; set; }

    /// <summary>
    /// Numero de telefono del emisor
    /// </summary>

    [System.Text.Json.Serialization.JsonPropertyName("telefono")]

    [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]
    [System.ComponentModel.DataAnnotations.Required]
    [System.ComponentModel.DataAnnotations.StringLength(30, MinimumLength = 8)]
    public string Telefono { get; set; }

    /// <summary>
    /// Correo electronico del emisor
    /// </summary>

    [System.Text.Json.Serialization.JsonPropertyName("correo")]

    [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]
    [System.ComponentModel.DataAnnotations.Required]
    [System.ComponentModel.DataAnnotations.StringLength(100, MinimumLength = 3)]
    public string Correo { get; set; }


}

[System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "10.8.0.0 (Newtonsoft.Json v13.0.3.0)")]
public partial class DetalleDTE
{
    /// <summary>
    /// Numero correlativo.
    /// </summary>

    [System.Text.Json.Serialization.JsonPropertyName("noItem")]

    [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]
    public int NoItem { get; set; }

    /// <summary>
    /// Codigo de generacion del documento reportado.
    /// </summary>

    [System.Text.Json.Serialization.JsonPropertyName("codigoGeneracion")]

    [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]
    [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
    [System.ComponentModel.DataAnnotations.RegularExpression(@"^[A-F0-9]{8}-[A-F0-9]{4}-[A-F0-9]{4}-[A-F0-9]{4}-[A-F0-9]{12}$")]
    public string CodigoGeneracion { get; set; }

    /// <summary>
    /// Tipo de Documento Tributario Electronico
    /// </summary>

    [System.Text.Json.Serialization.JsonPropertyName("tipoDoc")]

    [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]
    [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
    [System.ComponentModel.DataAnnotations.RegularExpression(@"^0[1-9]|1[0-5]$")]
    public string TipoDoc { get; set; }


}

[System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "10.8.0.0 (Newtonsoft.Json v13.0.3.0)")]
public partial class Motivo : object
{
    /// <summary>
    /// Fecha inicio de la contingencia
    /// </summary>

    [System.Text.Json.Serialization.JsonPropertyName("fInicio")]

    [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]
    [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
    [System.Text.Json.Serialization.JsonConverter(typeof(DateFormatConverter))]
    public System.DateTimeOffset FInicio { get; set; }

    /// <summary>
    /// Fecha de finalizacion de la contingencia
    /// </summary>

    [System.Text.Json.Serialization.JsonPropertyName("fFin")]

    [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]
    [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
    [System.Text.Json.Serialization.JsonConverter(typeof(DateFormatConverter))]
    public System.DateTimeOffset FFin { get; set; }

    /// <summary>
    /// Hora inicio de la contingencia.
    /// </summary>

    [System.Text.Json.Serialization.JsonPropertyName("hInicio")]

    [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]
    [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
    [System.ComponentModel.DataAnnotations.RegularExpression(@"^(0[0-9]|1[0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9]?$")]
    public string HInicio { get; set; }

    /// <summary>
    /// Hora fin de la contingencia.
    /// </summary>

    [System.Text.Json.Serialization.JsonPropertyName("hFin")]

    [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]
    [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
    [System.ComponentModel.DataAnnotations.RegularExpression(@"^(0[0-9]|1[0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9]?$")]
    public string HFin { get; set; }

    /// <summary>
    /// Debe seleccional del Catalogo de la Contingencias cualquiera de las 5 opciones que aplique segun el motivo.
    /// </summary>

    [System.Text.Json.Serialization.JsonPropertyName("tipoContingencia")]

    [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]
    //public MotivoTipoContingencia TipoContingencia { get; set; }
    public int TipoContingencia { get; set; }

    /// <summary>
    /// Descripcion del motivo de la contingencia.
    /// </summary>

    [System.Text.Json.Serialization.JsonPropertyName("motivoContingencia")]

    [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]
    [System.ComponentModel.DataAnnotations.StringLength(500)]
    public string MotivoContingencia { get; set; }


}

[System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "10.8.0.0 (Newtonsoft.Json v13.0.3.0)")]
public enum IdentificacionAmbiente
{

    [System.Runtime.Serialization.EnumMember(Value = @"00")]
    _00 = 0,


    [System.Runtime.Serialization.EnumMember(Value = @"01")]
    _01 = 1,


}

[System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "10.8.0.0 (Newtonsoft.Json v13.0.3.0)")]
public enum EmisorTipoDocResponsable
{

    [System.Runtime.Serialization.EnumMember(Value = @"36")]
    _36 = 0,


    [System.Runtime.Serialization.EnumMember(Value = @"13")]
    _13 = 1,


    [System.Runtime.Serialization.EnumMember(Value = @"02")]
    _02 = 2,


    [System.Runtime.Serialization.EnumMember(Value = @"03")]
    _03 = 3,


    [System.Runtime.Serialization.EnumMember(Value = @"37")]
    _37 = 4,


}

[System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "10.8.0.0 (Newtonsoft.Json v13.0.3.0)")]
public enum EmisorTipoEstablecimiento
{

    [System.Runtime.Serialization.EnumMember(Value = @"01")]
    _01 = 0,


    [System.Runtime.Serialization.EnumMember(Value = @"02")]
    _02 = 1,


    [System.Runtime.Serialization.EnumMember(Value = @"04")]
    _04 = 2,


    [System.Runtime.Serialization.EnumMember(Value = @"07")]
    _07 = 3,


    [System.Runtime.Serialization.EnumMember(Value = @"20")]
    _20 = 4,


}

[System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "10.8.0.0 (Newtonsoft.Json v13.0.3.0)")]
public enum MotivoTipoContingencia
{

    _1 = 1,


    _2 = 2,


    _3 = 3,


    _4 = 4,


    _5 = 5,


}

[System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "10.8.0.0 (Newtonsoft.Json v13.0.3.0)")]
internal class DateFormatConverter : System.Text.Json.Serialization.JsonConverter<System.DateTimeOffset>
{
    public override System.DateTimeOffset Read(ref System.Text.Json.Utf8JsonReader reader, System.Type typeToConvert, System.Text.Json.JsonSerializerOptions options)
    {
        var dateTime = reader.GetString();
        if (dateTime == null)
        {
            throw new System.Text.Json.JsonException("Unexpected JsonTokenType.Null");
        }

        return System.DateTimeOffset.Parse(dateTime);
    }

    public override void Write(System.Text.Json.Utf8JsonWriter writer, System.DateTimeOffset value, System.Text.Json.JsonSerializerOptions options)
    {
        writer.WriteStringValue(value.ToString("yyyy-MM-dd"));
    }
}
